### ISSUE TITLE
Will tagging my existing music cause duplicate uploads to iB?

### ISSUE THREAD

**Issue by jordanbates** [ctrueden/beets-ibroadcast#10]
I'd like to import my music collection into Beets and enable this plugin. Is my assumption correct that using the autotagger, thus changing the metadata of my music files, would keep them from matching the MD5 checksum of the existing files in iBroadcast? If so, is there some way around that? I'd like to fix up my library with the autotagger without having to completely delete/reimport my iBroadcast library if possible.

Thanks for this plugin by the way, this looks really awesome!

**Comment by ctrueden** [comment]
@jordanbates Good question, and yeah, I think you're right. If I recall correctly, the iBroadcast MD5 checksum is over the whole file, so any changes to ID3 tags are going to change the checksum, unfortunately. My situation when I wrote the plugin was that I already had my stuff in beets, and wanted to upload from there to iBroadcast.

That said, the plugin adds flexible attributes `ib_uploadtime` and `ib_trackid` to each track it uploads, and only reuploads when the `ib_uploadtime` timestamp is older than the file's last modified timestamp. So, to avoid reuploading everything, you could:

1. Import all your stuff into beets.
2. Use the [iBroadcast Python client](https://github.com/ctrueden/ibroadcast-python) to download your iBroadcast metadata into a local data structure.
3. Match up the IDs of your iBroadcast tracks with those in beets by comparing album/artist/title metadata. Of course, after autotagging them, some of that metadata may differ from when you originally uploaded it to iBroadcast.
4. Once you have a "best effort" matchup, you can use the beets API to add the `ib_uploadtime` and `ib_trackid` flexible attributes to the matching tracks in your beets DB, setting the `ib_uploadtime` to `datetime.now()` or whatever new enough date.
5. Then enable the beets-ibroadcast plugin, and run it on a very small query to see whether it deletes+reuploads the matching tracks, or is satisfied that the tracks "haven't changed" since the last upload.

I think this will work because there are two layers of filtering for upload: the filtering done by beets-ibroadcast using the `ib_uploadtime` attribute, followed by the checksumming and filtering of files with checksums already in the iBroadcast checksums list.

Happy to help further if you need further guidance. I've been planning some improvements to this plugin for a while now—mostly relating to bidirectional syncing of metadata like playlists, rather than only the beets-to-iBroadcast direction. But as is so often the case with hobby projects, it's hard to make the time. I'll be happy if the plugin is useful to you in its current form, though!

**Comment by jordanbates** [comment]
Thanks for your thought out answer! I played with the python client a bit but ultimately I think it will be easier to import into beets and then do a full re-upload to iBroadcast, seeing as I don't actually have too much of a difference between my local collection and iBroadcast.

Bidirectional syncing of playlists would be really nice, but I understand how hobby projects go. (And playlist syncing with Spotify sounds like a dream. I've been pondering how to sync my local collection and Spotify in a sane way)

**Comment by ctrueden** [comment]
@jordanbates Sounds good! Reuploading everything is definitely the simplest way forward, as long as you don't mind losing your stats like thumbs-ups and so on. (Does iBroadcast track play counts? I can't remember... but these are the questions that keep me up at night :laughing:) At some point it would be cool to figure out whether the iBroadcast API supports programmatic setting of such metadata, because then we could just populate it again when a reupload happens.
