### ISSUE TITLE
Errors out if a tag was removed both locally and remotely

### ISSUE THREAD

**Issue by auratheenby** [ctrueden/beets-ibroadcast#7]
So I made the mistake of deleting some tags on the ibroadcast side, which left some of my library with dangling references to those tags. I would expect that beets would detect that situation and remove all the references in response, but instead it just errors out, preventing sync.
This line specifically, with a KeyError of the tagid.
https://github.com/ctrueden/beets-ibroadcast/blob/ae9f4d252bc5ac7d7222c67034c5cfac1f6088f0/beetsplug/ibroadcast/command.py#L254

I ended up deleting all tags on both ends and doing "beet modify ib_tagids!", which I don't recommend, it didn't like it very much and I had to force-reupload everything. It's fortunate that I have a (relatively) small enough library that I can do things like that, others might not be so lucky.

I feel this is a relatively easy fix, so I there's a good chance I'll open a PR. Might be hard to test though, as I'd rather not wreck my library again.

**Comment by auratheenby** [comment]
@ctrueden thanks! That's along the lines of what I was thinking.
I also just encountered the issue again with a playlist - one that is now empty on ib's side because of the reupload, and therefore has changed so beets won't sync it. But it's still referenced by beets, so deleting it from ib makes beets throw a fit. I'll start with the ids, but this does make me tempted to tackle backwards playlist syncing & conflicts afterwards. 👀

**Comment by ctrueden** [comment]
@auratheenby Awesome! Best of luck. My tentative plan for the next major revision of this plugin—assuming I ever end up having time for such a thing—is to make the syncing of different aspects explicit with various flags, and in some cases explicitly one-directional, like `beets ibroadcast --upload-playlists`, `beets ibroadcast --download-playlists`, `beets ibroadcast --sync-tags`. If you decide to look into better playlist syncing, that's the approach I would recommend, since unlike with tags, playlists can end up with bidirectional syncing conflicts, same as can happen e.g. when doing a git merge. But just fixing the handling of no-longer-present remote keys with defensive programming shouldn't require such considerations, hopefully.
